CC	= gcc
CFLAGS	= -m32 -Wall  -O0 -g3 -gdwarf-2  -nostdinc -Iinclude  \
	-fstrength-reduce -fomit-frame-pointer -fno-stack-protector -fno-builtin  
LD	= ld
LDFLAGS = -m elf_i386
CPP	= cpp -nostdinc -Iinclude 

AR = ar 
STRIP   = strip
OBJCOPY = objcopy